apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      exemplarTraceIdDestinations:
        - name: trace_id
          urlDisplayLabel: View trace
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: axion-stack
