name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma
        run: bun run db:generate

      - name: Build database package
        run: cd packages/database && bun run db:build

      - name: Generate Paraglide i18n
        run: cd apps/web && npx paraglide-js compile --project ./project.inlang --outdir ./src/paraglide

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run check-types

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx semantic-release
