name: Validate PR

on:
  pull_request:
    branches: [main, master]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run check-types

      - name: Build
        run: bun run build

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        if: github.event_name == 'pull_request'
